### ISSUE TITLE
ISSUE 1 : 대문 사진이 안바뀝니다....

### ISSUE THREAD

**Issue by KoEonYack** [KoEonYack/dbproject#1]
style.css에서 background image가 있는데 기존의 사진을 다른 사진으로 바꾸면 완전 흰색깔 배경만 나옵니다.. 수정해주실분

**Comment by gritYCDA** [comment]
방금 봤네 ㅠㅠㅠ 해결된 거?

**Comment by KoEonYack** [comment]
ㄴㄴㄴㄴㄴㄴㄴ 누군가 고쳐주시면 감사하겠습니당

**Comment by KoEonYack** [comment]
수정했습니다.
